[project]
name = "python-fofa-sy"
version = "0.0.1"
description = "Fofa引擎的Python接口 | A Python api for fofa assets-scan engine"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "colorama>=0.4.6",
    "pytest>=7.4.4",
    "pyyaml>=6.0.1",
    "requests>=2.31.0",
]
